# Generated by Django 4.0 on 2021-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCheckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsDropDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsRadioButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='متن سوال')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_required', models.BooleanField(default=False, verbose_name='مورد نیاز')),
            ],
        ),
        migrations.CreateModel(
            name='RadioButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='متن سوال')),
                ('add_item', models.ManyToManyField(to='SampleForms.ItemsRadioButton')),
            ],
        ),
        migrations.CreateModel(
            name='DropDownQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='متن سوال')),
                ('add_item', models.ManyToManyField(to='SampleForms.ItemsDropDown')),
            ],
        ),
        migrations.CreateModel(
            name='CheckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='متن سوال')),
                ('add_item', models.ManyToManyField(to='SampleForms.ItemsCheckBox')),
            ],
        ),
    ]
