# Generated by Django 3.2.7 on 2021-11-19 00:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0004_alter_pricingreport_table'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ عضویت')),
                ('last_update', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی')),
                ('last_login', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('is_manager', models.BooleanField(default=False, help_text='مدیر ارشد میتواند سازمان تعریف کند و به تمامی گزارشات و کاربران دسترسی دارد.', verbose_name='مدیر ارشد')),
                ('product_groups', models.TextField(blank=True, null=True, verbose_name='دسترسی گروه محصولات')),
                ('phone', models.CharField(help_text='همراه با صفر وارد شود.', max_length=11, null=True, verbose_name='تلفن همراه')),
                ('verified_email', models.BooleanField(default=False, verbose_name='ایمیل تایید\u200cشده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('dashboards', models.ManyToManyField(blank=True, to='dashboards.Dashboard', verbose_name='دسترسی داشبوردها')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': '   کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'تلفن همراه'), ('email', 'پست الکترونیکی')], max_length=10, verbose_name='نوع')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تلاش\u200cها')),
                ('code', models.PositiveSmallIntegerField(verbose_name='کد')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد احراز',
                'verbose_name_plural': 'کدهای احراز',
                'ordering': ['-created_at'],
            },
        ),
    ]
