# Generated by Django 4.0 on 2021-12-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SampleForms', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پرسشنامه')),
                ('checkbox', models.ManyToManyField(to='SampleForms.CheckBox')),
                ('drop_down_question', models.ManyToManyField(to='SampleForms.DropDownQuestion')),
                ('open_question', models.ManyToManyField(to='SampleForms.OpenQuestion')),
                ('radio_button', models.ManyToManyField(to='SampleForms.RadioButton')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
